php:
    image: php-7
    ports:
        - "8082:80"
    volumes:
        - ./:/var/www/html
    links:
        - db

db:
    image: mysql:5.6
    ports:
        - "3636:3306"
    environment:
        MYSQL_ROOT_PASSWORD: 1234
    volumes:
        - ./mysql_directory:/var/lib/mysql_directory
phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - "8888:80"
    links:
        - db
